<HTML>
  
	<head>
 
	<base target="main">
 
	</head>

  <BODY >
    <TABLE ALIGN="Center" WIDTH="60%" BORDER="0">
      <TR HEIGHT="30"  ALIGN="Center">
        <TD><A href="Catalog.asp" TARGET="main">产品</A></TD>
      </TR>
      <TR HEIGHT="30"   ALIGN="Center">
        <TD><A href="Car.asp" TARGET="main">查看购物车</A></TD>
      </TR>
      <TR HEIGHT="30" ALIGN="Center">
        <TD><a href="Order.asp" TARGET="main">在线付款</a></TD>
      </TR>
    </TABLE>
  </BODY>
</HTML>